defaults:
    - tdmpc2
    - _self_

# environment
seed: 1
task: ms-peg-insertion-semi
obs: rgb
num_envs: 16

# evaluation
eval_episodes: 10
eval_freq: 2000

# training
steps: 4_000_000
batch_size: 256
steps_per_update: 4 # utd = steps_per_update / num_envs (in this implementation)
buffer_size: 300_000
save_freq: 500_000
demo_sampling_ratio: 0.5 # Demonstration sampling ratio
policy_pretraining: true
use_demos: ???
seed_scheduler: false
demo_success_only: false

# pretraining
pretrain:
    n_epochs: 100000
    eval_freq: 5000
    log_freq: 500

# logging
wandb_project: demo3
wandb_entity: ???
wandb_silent: true
disable_wandb: true
save_csv: false

# reward learning
enable_reward_learning: true
n_stages: ???
demo_path: ??? #/path/to/demos/data.pkl
discriminator:
    disc_lr: 3e-4
    batch_size: 256
n_demos: 10
